### ISSUE TITLE
Integration does not show up in the add integration dialog

### ISSUE THREAD

**Issue by ocampana** [h4de5/home-assistant-toshiba_ac#33] opened 2021-12-15 21:06 UTC
I am running HomeAssistant 2021.12.2 in a docker image. I followed the instructions creating custom components and copying the toshiba_ac folder in it.

After the roobt I see a log from home assistant that states that it found the custom component, but I canno add it because it does not show up in the add integration dialog.

What can I do?

**Comment by h4de5** [comment] 2022-01-01 10:44
hi - sorry. for the long wait.

can you post the relevant part from your logs? which part of the release did you put into your custom_components directory?

**Comment by ocampana** [comment] 2022-01-09 10:09
Hi, no problem for the delay, I've been on vacation as well.

I just updated to Home Assistant 2021.12.8, integration shows up but when I log in I get this error:
```

Traceback (most recent call last):                                                                                                                          
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform                                                
    await asyncio.shield(task)                                                                                                                              
  File "/config/custom_components/toshiba_ac/sensor.py", line 40, in async_setup_entry                                                                      
    devices: List[ToshibaAcDevice] = await device_manager.get_devices()                                                                                     
  File "/usr/local/lib/python3.9/site-packages/toshiba_ac/device_manager.py", line 107, in get_devices                                                      
    device = ToshibaAcDevice(                                                                                                                               
  File "/usr/local/lib/python3.9/site-packages/toshiba_ac/device.py", line 88, in __init__                                                                  
    self.load_supported_merit_features(merit_feature, ac_model_id)                                                                                          
  File "/usr/local/lib/python3.9/site-packages/toshiba_ac/device.py", line 117, in load_supported_merit_features                                            
    floor, _, cdu_silent, pure_ion, fireplace, heating_8c, _, _ = struct.unpack('????????', bytes.fromhex('0' + '0'.join(f'{merit_byte:08b}')))             
ValueError: non-hexadecimal number found in fromhex() arg at position 1                                                                                     
2022-01-09 10:06:48 ERROR (MainThread) [homeassistant.components.climate] Error while setting up toshiba_ac platform for climate                            
Traceback (most recent call last):                                                                                                                          
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform                                                
    await asyncio.shield(task)                                                                                                                              
  File "/config/custom_components/toshiba_ac/climate.py", line 64, in async_setup_entry                                                                     
    devices = await device_manager.get_devices()                                                                                                            
  File "/usr/local/lib/python3.9/site-packages/toshiba_ac/device_manager.py", line 107, in get_devices                                                      
    device = ToshibaAcDevice(                                                                                                                               
  File "/usr/local/lib/python3.9/site-packages/toshiba_ac/device.py", line 88, in __init__                                                                  
    self.load_supported_merit_features(merit_feature, ac_model_id)                                                                                          
  File "/usr/local/lib/python3.9/site-packages/toshiba_ac/device.py", line 117, in load_supported_merit_features                                            
    floor, _, cdu_silent, pure_ion, fireplace, heating_8c, _, _ = struct.unpack('????????', bytes.fromhex('0' + '0'.join(f'{merit_byte:08b}')))             
ValueError: non-hexadecimal number found in fromhex() arg at position 1                                                                                     
```

Ths the result is that I can now add the integration, but I see no device. Any hint?

**Comment by h4de5** [comment] 2022-01-10 06:40
it seems your device has "strange" values set in its merit_byte. Which device do you try to control using the extension? is it in the supported device list?

Can you try to use an example from the toshiba Api directly? you can find them here: https://github.com/KaSroka/Toshiba-AC-control

**Comment by h4de5** [comment] 2022-01-10 06:41
it seems there is another one having a similiar issue: https://github.com/KaSroka/Toshiba-AC-control/issues/11

**Comment by ocampana** [comment] 2022-01-16 07:49
> it seems your device has "strange" values set in its merit_byte. Which device do you try to control using the extension? is it in the supported device list?
> 
> Can you try to use an example from the toshiba Api directly? you can find them here: https://github.com/KaSroka/Toshiba-AC-control

The devices are:

- TOSHIBA SHORAI EDGE RAS-B13N4KVSG-E UI
- Toshiba RAS-2M18U2AVG-E U.E.MULTISPLIT
- Toshiba SEIYA RAS-B13J2KVG-E UI

**Comment by ocampana** [comment] 2022-01-17 09:48
Here's the output you requested.

```
[2022-01-17 10:44:22,466] DEBUG    toshiba_ac.http_api: Sending POST to https://toshibamobileservice.azurewebsites.net/api/Consumer/Login with params=None, json={'Username': 'TOSHIBA_USER', 'Password': 'TOSHIBA_PASS'}, headers={'Content-Type': 'application/json'}
[2022-01-17 10:44:22,700] DEBUG    toshiba_ac.http_api: Response code: 200, JSON: {'ResObj': {'access_token': '-EaDqxnwMh7f7fNowKSuZmndbuKMRyJ0t1WbDPVVNQJp-elGR5NUVMXxXGR_lmBnBt7PqcPyq-mE8XjAQV_lyz35-N3jTgtMCUtumG7LNq_xOFRjWP_0lrbVBp66ovPoGCdaaO0dCdEqZ0gDQLNQKlkJX4eJZ2IUUC2_bRrdd2QFQ3BxxiEsz347hbuJl1qN16Jo--g1AEo0kmh7sO_3NQ', 'token_type': 'bearer', 'expires_in': 1576799999, 'consumerId': '14e9e9da-d648-4c7b-abf6-f2bcbb869533', 'countryId': 110, 'consumerMasterId': 'd45a92ca984a7055fa239253185329d688bd136e851043ec1dcb41e502dd246b'}, 'IsSuccess': True, 'Message': 'Success', 'StatusCode': 'Success'}
[2022-01-17 10:44:22,700] DEBUG    toshiba_ac.http_api: Sending POST to https://toshibamobileservice.azurewebsites.net/api/Consumer/RegisterMobileDevice with params=None, json={'DeviceID': 'TOSHIBA_USER_3e6e4eb5f0e5aa40', 'DeviceType': '1', 'Username': 'TOSHIBA_USER'}, headers={'Content-Type': 'application/json', 'Authorization': 'bearer -EaDqxnwMh7f7fNowKSuZmndbuKMRyJ0t1WbDPVVNQJp-elGR5NUVMXxXGR_lmBnBt7PqcPyq-mE8XjAQV_lyz35-N3jTgtMCUtumG7LNq_xOFRjWP_0lrbVBp66ovPoGCdaaO0dCdEqZ0gDQLNQKlkJX4eJZ2IUUC2_bRrdd2QFQ3BxxiEsz347hbuJl1qN16Jo--g1AEo0kmh7sO_3NQ'}
[2022-01-17 10:44:22,990] DEBUG    toshiba_ac.http_api: Response code: 200, JSON: {'ResObj': {'DeviceId': 'TOSHIBA_USER_3e6e4eb5f0e5aa40', 'HostName': 'toshibasmaciothubprod.azure-devices.net', 'PrimaryKey': 'nSe9+5/qufG0aqHp2kVXp8pLuPKIjq2I6jrZPwHrZiQ=', 'SecondaryKey': 'BHnBUUAoxcUxJ9NsNWttCPMIEgEmEETCi85xqvG9eX4=', 'SasToken': 'SharedAccessSignature sr=toshibasmaciothubprod.azure-devices.net%2Fdevices%2FTOSHIBA_USER_3e6e4eb5f0e5aa40&sig=3ZC%2FyDxOVxzJzeTMtwxyusqJPJCxXt8VlGYfqBIcsf0%3D&se=4796012663', 'RegisterDate': '2022-01-17T09:43:15.92'}, 'IsSuccess': True, 'Message': 'Success', 'StatusCode': 'Success'}
[2022-01-17 10:44:23,317] DEBUG    __main__: AMQP SAS token: SharedAccessSignature sr=toshibasmaciothubprod.azure-devices.net%2Fdevices%2FTOSHIBA_USER_3e6e4eb5f0e5aa40&sig=3ZC%2FyDxOVxzJzeTMtwxyusqJPJCxXt8VlGYfqBIcsf0%3D&se=4796012663
[2022-01-17 10:44:23,317] DEBUG    toshiba_ac.http_api: Sending GET to https://toshibamobileservice.azurewebsites.net/api/AC/GetConsumerACMapping with params={'consumerId': '14e9e9da-d648-4c7b-abf6-f2bcbb869533'}, headers={'Content-Type': 'application/json', 'Authorization': 'bearer -EaDqxnwMh7f7fNowKSuZmndbuKMRyJ0t1WbDPVVNQJp-elGR5NUVMXxXGR_lmBnBt7PqcPyq-mE8XjAQV_lyz35-N3jTgtMCUtumG7LNq_xOFRjWP_0lrbVBp66ovPoGCdaaO0dCdEqZ0gDQLNQKlkJX4eJZ2IUUC2_bRrdd2QFQ3BxxiEsz347hbuJl1qN16Jo--g1AEo0kmh7sO_3NQ'}
[2022-01-17 10:44:23,566] DEBUG    toshiba_ac.http_api: Response code: 200, JSON: {'ResObj': [{'GroupId': '3f326dce-0087-412e-be24-155d0accde01', 'GroupName': 'All', 'ConsumerId': '14E9E9DA-D648-4C7B-ABF6-F2BCBB869533', 'TimeZone': 'W. Europe Standard Time', 'ACList': [{'Id': 'ee1432a7-0f99-4112-a4b3-4cd2b67923dc', 'DeviceUniqueId': 'c1ddd5d5-1a88-4084-b3c9-db20d34a267d', 'Name': 'Mansarda', 'ACModelId': '2', 'Description': 'AC_c1ddd5d5-1a88-4084-b3c9-db20d34a267d', 'CreatedDate': '12/14/2021 4:07:28 PM', 'ACStateData': '3141154131640010140bfe0b000010ff000000', 'FirmwareUpgradeStatus': '', 'URL': '', 'File': '', 'MeritFeature': 'ac00', 'AdapterType': '0', 'FirmwareVersion': '3.3.01', 'FirmwareCode': '0000', 'ModeValues': [{'Mode': '41', 'Temp': '15', 'FanSpeed': '41'}, {'Mode': '42', 'Temp': '16', 'FanSpeed': '31'}, {'Mode': '43', 'Temp': '18', 'FanSpeed': '41'}, {'Mode': '44', 'Temp': '16', 'FanSpeed': '41'}, {'Mode': '45', 'Temp': '16', 'FanSpeed': '31'}], 'Control': None}, {'Id': '521b51c1-e293-4149-b73d-940a6c709bd2', 'DeviceUniqueId': '0a106805-4a08-4306-b2db-fae0714eafa6', 'Name': 'Piano terra', 'ACModelId': '2', 'Description': 'AC_0a106805-4a08-4306-b2db-fae0714eafa6', 'CreatedDate': '12/14/2021 3:40:39 PM', 'ACStateData': '31431634316400101b0bfe0b000010ff000000', 'FirmwareUpgradeStatus': '', 'URL': '', 'File': '', 'MeritFeature': '2c00', 'AdapterType': '0', 'FirmwareVersion': '3.3.01', 'FirmwareCode': '0000', 'ModeValues': [{'Mode': '41', 'Temp': '18', 'FanSpeed': '34'}, {'Mode': '42', 'Temp': '16', 'FanSpeed': '34'}, {'Mode': '43', 'Temp': '16', 'FanSpeed': '34'}, {'Mode': '44', 'Temp': '16', 'FanSpeed': '41'}, {'Mode': '45', 'Temp': '18', 'FanSpeed': '35'}], 'Control': None}]}], 'IsSuccess': True, 'Message': 'Success', 'StatusCode': 'Success'}
[2022-01-17 10:44:23,567] DEBUG    toshiba_ac.device_manager: Found devices: [ToshibaAcDeviceInfo(ac_id='ee1432a7-0f99-4112-a4b3-4cd2b67923dc', ac_unique_id='c1ddd5d5-1a88-4084-b3c9-db20d34a267d', ac_name='Mansarda', initial_ac_state='3141154131640010140bfe0b000010ff000000', firmware_version='3.3.01', merit_feature='ac00', ac_model_id='2'), ToshibaAcDeviceInfo(ac_id='521b51c1-e293-4149-b73d-940a6c709bd2', ac_unique_id='0a106805-4a08-4306-b2db-fae0714eafa6', ac_name='Piano terra', initial_ac_state='31431634316400101b0bfe0b000010ff000000', firmware_version='3.3.01', merit_feature='2c00', ac_model_id='2')]
[2022-01-17 10:44:23,567] ERROR    asyncio: Task exception was never retrieved
future: <Task finished name='Task-2' coro=<App.init() done, defined at /home/ottavio/Progetti/Toshiba-AC-control/samples/toshiba_ac_gui.py:134> exception=ValueError('non-hexadecimal number found in fromhex() arg at position 1')>
Traceback (most recent call last):
  File "/home/ottavio/Progetti/Toshiba-AC-control/samples/toshiba_ac_gui.py", line 139, in init
    devices = await self.device_manager.get_devices()
  File "/home/ottavio/Progetti/Toshiba-AC-control/venv/lib/python3.9/site-packages/toshiba_ac/device_manager.py", line 107, in get_devices
    device = ToshibaAcDevice(
  File "/home/ottavio/Progetti/Toshiba-AC-control/venv/lib/python3.9/site-packages/toshiba_ac/device.py", line 88, in __init__
    self.load_supported_merit_features(merit_feature, ac_model_id)
  File "/home/ottavio/Progetti/Toshiba-AC-control/venv/lib/python3.9/site-packages/toshiba_ac/device.py", line 117, in load_supported_merit_features
    floor, _, cdu_silent, pure_ion, fireplace, heating_8c, _, _ = struct.unpack('????????', bytes.fromhex('0' + '0'.join(f'{merit_byte:08b}')))
ValueError: non-hexadecimal number found in fromhex() arg at position 1
```

**Comment by ocampana** [comment] 2022-01-17 09:53
I can tell something more: I manually patched the toshiba-ac package in my virtualenv as indicated in https://github.com/KaSroka/Toshiba-AC-control/issues/11#issuecomment-1004730122 and it works perfectly!

**Comment by h4de5** [comment] 2022-01-17 10:11
Great news. Can comment your progress on the linked issue - maybe the author can include the fix in the next release.

Can I close this?

**Comment by ocampana** [comment] 2022-01-19 08:23
As a double check, I manually pathced the dependency in my home assistant instance and I can see the units working.

Therefore I think you can close this issue, I'll make a pull request for toshiba-ac.

Thank you for your support.

**Comment by h4de5** [comment] 2022-01-22 18:16
Add a new release - let me know if the problem is fixed.

**Closed** 2022-01-22 18:17 UTC
