### ISSUE TITLE
temperature does not update

### ISSUE THREAD

**Issue by PaoloTo** [h4de5/home-assistant-toshiba_ac#82] opened 2022-08-05 21:03 UTC
Dear, thanks for the hard work creating this integration. It works like a charm but there is a small problem. The temperature sensors (interior and on the external units) are updated only when i open the toshiba app on my phone. Otherwise the sensors on ha retain the last value. At time o writing the last update is yesterday. I never use the the toshiba app becouse i prefer use this one. Someone have the same iussue? (I have this since i've added the integration, at least 2 month ago)
Thank you

**Comment by blbeczech82** [comment] 2022-09-30 12:38
+1
What you describe happened to me and intergration reload was failing until I opened the app on mobile.

Normally it updates itself every :00 and :30 minutes (usually). Seems like automated push from cloud, I couldn't find refresh time in source code.
I'm curious if I can change somewhere:
- update period
- temperature decimals (now it is rounded to whole number)

**Comment by helljol** [comment] 2023-01-23 06:33
Hi @h4de5 , I do have the same questions the current temperature does not seems to be updated when it changes. Is there a way to change the update period ?

Thanks you for this integration

**Comment by Kodlitko** [comment] 2024-07-09 08:21
Hi all,

I have same issue last few weeks - outdoor temperature in HA is updated only few times a day and always when I open official Toshiba app. I am running HA on RaspberryPi 3B with official HAOS: Core 2024.7.1, Supervisor 2024.06.2, OS 12.4, Frontend 20240705.0, latest HACS  and Toshiba AC release.

But I also have a testing instance of HA hosted as virtual PC in cloud and it is used to test integrations, updates etc. before I run them on my home system - and here the temperature is updating more frequently. It is exactly the same HAOS version but running in x86_64 virtual. But I don't assume that different system architecture can affect this.

For integration I have another Toshiba Home AC account (same mail, different username) - temperature is updated no matter which of two account is used in integration or Android app. Temperature is updated even if integration is logged with account1 and I open Android app logged with account2.

Here you can compare two temperature graphs from my HA instances:

HA instance on RPi
![image](https://github.com/h4de5/home-assistant-toshiba_ac/assets/42772673/0a914711-3551-492e-b6ad-20a3a643ffc3)

Testing HA instance in virtual
![image](https://github.com/h4de5/home-assistant-toshiba_ac/assets/42772673/f3a8a3b9-2c33-4dbd-8591-a52965ddec9d)

**Comment by felixmueller** [comment] 2024-07-09 08:32
Hi @Kodlitko,
just a quick addition regarding the architecture:
I am running HA on aarch64 and the temperature is updating regularly.

**Comment by Kodlitko** [comment] 2024-07-09 10:01
I think architecture has no effect on the update frequency - I mentioned it only to provide the most accurate information about my config

**Comment by blue0mt** [comment] 2024-07-27 08:33
I have the exact same issue. The temperature updates rarely, maybe once a day but it also when I open the toshiba app. 

Does anyone know a fix or a workaround for this issue? My automations won't work properly because they depend on outdoor temperature. :/

**Comment by acseven** [comment] 2024-07-31 08:11
Same behavior here. Temperature sensors update at random intervals, though usually a few hours.

![image](https://github.com/user-attachments/assets/fb4ca975-6760-4a53-8e3d-6cc7daf9c8d8)

The exterior unit's sensor has the same behavior:

![image](https://github.com/user-attachments/assets/f62cb743-cb8a-45d9-baf0-02e99239f6bb)

**Comment by h4de5** [comment] 2024-08-02 06:50
it seems there are different models out there. my device sets the outdoor sensor to unavailable when I turn off the climate.
regarding the decimals, I can't remember if i had the before. at least the toshiba app shows whole numbers for me too.

@KaSroka is it possible to check if the app is sending some kind of update-request to the server when its opened?

**Comment by Kodlitko** [comment] 2024-08-05 08:41
@h4de5 you're right.

I have three console units - two newer models and one older model with separate outdoor unit. In Toshiba app I can see outside temperature for all of them, but for older one only when it is turned on (must be heating or cooling mode, not fan only). In Home Assistant when older unit is off, temperature is shown as N/A.

![image](https://github.com/user-attachments/assets/5c4a0cee-9845-4870-9398-c568e0a12cc1)

But this issue occurs on all my units / temperature sensors.

**Comment by KaSroka** [comment] 2024-08-12 18:19
Temperature is send over AMQP from cloud. So we can only wait for new notification. App logs in every time you open it, probably triggering extra update. Also for my device I have the temp updates periodically. We also have a failsafe that pools the state (and with it the temperature) every 30mins. So we should see temp updates at least every 30min.

**Comment by acseven** [comment] 2024-08-12 18:23
> Temperature is send over AMQP from cloud. So we can only wait for new notification. App logs in every time you open it, probably triggering extra update. Also for my device I have the temp updates periodically. We also have a failsafe that pools the state (and with it the temperature) every 30mins. So we should see temp updates at least every 30min.

I can't confirm the every 30min update on my device. This is for this entire week and the temp change was because I opened the Toshiba app today:

![s0](https://github.com/user-attachments/assets/dd4987a7-e150-480a-93e4-050c92b835b6)

Same thing for one of the interior units:
![s01](https://github.com/user-attachments/assets/2c27ef21-8e87-472a-a070-5273679e3497)

**Comment by KaSroka** [comment] 2024-08-12 21:36
I think I know what is happening. Currently requests are made at constant times and there are so many of us that rate limiting kicks in on the azure endpoint. When you try to get the state at :00 or at :30 it will fail with 403 but after 2 minutes it starts working again. I will try to randomise the requests and push fix soon.

**Comment by blue0mt** [comment] 2024-08-13 05:44
I also cannot confirm that it updates every 30 minutes. I have the AC on but the outdoor temperature was last updated 3 days ago.

**Comment by KaSroka** [comment] 2024-08-14 11:49
@acseven @blue0mt do you still see the issue with latest version of the integration?

**Comment by h4de5** [comment] 2024-08-14 12:55
several restarts later it still is available.

**Comment by acseven** [comment] 2024-08-14 18:51
> @acseven @blue0mt do you still see the issue with latest version of the integration?

I think that solved it! Thanks!

![image](https://github.com/user-attachments/assets/93064b5d-3223-4b78-9c42-2fc87577df0f)

**Comment by blbeczech82** [comment] 2024-08-14 18:55
It seems to be updating every 15 minutes now. Thx for fix.

**Comment by blue0mt** [comment] 2024-08-15 06:02
Yes, seems to be working better now. Thank you!

**Comment by Kodlitko** [comment] 2024-08-15 12:38
Hello, I can confirm 24 hours after update - temperature updates are more frequent now :-) Thank you.
![image](https://github.com/user-attachments/assets/bf0f5534-7aaa-4fa9-9a95-c04b43f1ca20)

**Comment by h4de5** [comment] 2024-08-16 03:10
closing as fixed in #199

**Closed by h4de5** 2024-08-16 03:10 UTC
