### ISSUE TITLE
unexpected error

### ISSUE THREAD

**Issue by chaniap** [h4de5/home-assistant-toshiba_ac#142] opened 2023-08-09 07:36 UTC
How to solve the problem that when I try to enter the password from the toshiba app into the integration it still says this and it's not working. But I can log into the original toshiba app just fine

**Comment by chaniap** [comment] 2023-08-09 07:48
![image](https://github.com/h4de5/home-assistant-toshiba_ac/assets/141813744/2477fb6a-9178-405e-9f48-d17fe908c743)

**Comment by h4de5** [comment] 2023-08-09 08:57
can you have a look at the home-assistant logs? and please confirm you are on the right toshiba app (not Toshiba NA)

**Comment by chaniap** [comment] 2023-08-09 09:08
Hi. I have an official toshiba home app

Logger: custom_components.toshiba_ac.config_flow
Source: custom_components/toshiba_ac/config_flow.py:41
Integration: toshiba_ac ([documentation](https://github.com/h4de5/home-assistant-toshiba_ac), [issues](https://github.com/h4de5/home-assistant-toshiba_ac/issues))
First occurred: 09:13:50 (1 occurrences)
Last logged: 09:13:50

Unexpected exception
Traceback (most recent call last):
  File "/home/homeassistant/lib/python3.10/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1089, in create_connection
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1119, in _create_connection_transport
  File "/usr/lib/python3.10/asyncio/sslproto.py", line 534, in data_received
  File "/usr/lib/python3.10/asyncio/sslproto.py", line 188, in feed_ssldata
  File "/usr/lib/python3.10/ssl.py", line 975, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/toshiba_ac/config_flow.py", line 77, in async_step_user
    data = await validate_input(self.hass, user_input)
  File "/home/homeassistant/.homeassistant/custom_components/toshiba_ac/config_flow.py", line 41, in validate_input
    sas_token = await device_manager.connect()
  File "/home/homeassistant/lib/python3.10/site-packages/toshiba_ac/device_manager.py", line 58, in connect
    await self.http_api.connect()
  File "/home/homeassistant/lib/python3.10/site-packages/toshiba_ac/utils/http_api.py", line 116, in connect
    res = await self.request_api(self.LOGIN_PATH, post=post, headers=headers)
  File "/home/homeassistant/lib/python3.10/site-packages/toshiba_ac/utils/http_api.py", line 97, in request_api
    async with method(url, **method_args) as response:
  File "/home/homeassistant/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/home/homeassistant/lib/python3.10/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/home/homeassistant/lib/python3.10/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/homeassistant/lib/python3.10/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/homeassistant/lib/python3.10/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/home/homeassistant/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/home/homeassistant/lib/python3.10/site-packages/aiohttp/connector.py", line 982, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host mobileapi.toshibahomeaccontrols.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')]

**Comment by h4de5** [comment] 2023-08-10 04:56
I cannot reproduce this behaviour. the url in question is provides by azure and has a valid certificate on my side.
is it possible that you have any self signed or unverified certificates within your home-assistant or network setup?

**Comment by chaniap** [comment] 2023-08-10 08:21
i dont know :-(

**Comment by elsonico** [comment] 2024-03-16 22:17
I have this very same issue now. Seems the mobileapi.toshibahomeaccontrols.com has expired again Mar 16 2024:

"Cannot connect to host mobileapi.toshibahomeaccontrols.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1007)')]"

![image](https://github.com/h4de5/home-assistant-toshiba_ac/assets/20227708/a40ca8fc-55e4-4686-b10c-f679fd589b5b)

**Comment by h4de5** [comment] 2024-03-18 02:05
it seems they noticed
![Screenshot_20240318-030442](https://github.com/h4de5/home-assistant-toshiba_ac/assets/6115324/5b7c0c90-c03f-4b0d-9718-624430a23a82)

**Comment by h4de5** [comment] 2024-06-16 13:56
closed as toshiba has updated their certificate and this issue should be fixed.

**Closed by h4de5** 2024-06-16 13:56 UTC
