### ISSUE TITLE
2022.6.14 can't works

### ISSUE THREAD

**Issue by ctalala** [h4de5/home-assistant-toshiba_ac#56] opened 2022-06-14 13:32 UTC
since today's update  
sensor.salon_outdoor_temperature has unit None which is unsupported for device_class temperature
3:10:10 PM – (WARNING) Sensor

Unable to prepare setup for platform toshiba_ac.climate: Platform not found (Exception importing custom_components.toshiba_ac.climate).

3:08:44 PM – (ERROR) setup.py
Unexpected exception importing platform custom_components.toshiba_ac.climate
3:08:44 PM – (ERROR) Toshiba AC (custom integration)

what do I have to do to get it working again?

**Comment by h4de5** [comment] 2022-06-14 14:13
if possible, please downgrade to previous version. It may take some time until I'll be able to fix it.

**Comment by tetienne** [comment] 2022-06-14 15:41
@ctalala What’s your HA version please?

**Comment by ctalala** [comment] 2022-06-14 15:43
My HA version is Home Assistant Core 2022.5.5

**Comment by tetienne** [comment] 2022-06-14 16:03
Duplicate of https://github.com/h4de5/home-assistant-toshiba_ac/issues/57 for the climate error. 
 
> sensor.salon_outdoor_temperature has unit None which is unsupported for device_class temperature

About this one, I will check what can be wrong. I have noticed something strange within the sensor platform.

@h4de5 [native_value](https://github.com/h4de5/home-assistant-toshiba_ac/blob/main/custom_components/toshiba_ac/sensor.py#L175) must be used instead of state.

**Comment by ctalala** [comment] 2022-06-14 16:10
i downgrade and install 2022.4.1 and I've got all sensors !

**Comment by h4de5** [comment] 2022-06-14 19:18
@tetienne maybe something that helps: some devices no longer return the outdoor temperature if turned off. and some devices do not have power consumption sensors.

**Comment by tetienne** [comment] 2022-06-14 19:22
@h4de5 thx for the tips!

@ctalala With the downgrade, do you still have the warning related to the sensor?

**Comment by ctalala** [comment] 2022-06-15 09:43
With downgrade all works perfectly and no warning in log

**Comment by h4de5** [comment] 2022-07-18 10:56
still an issue with current version?

**Closed as completed** 2022-07-19 15:57 UTC
