### ISSUE TITLE
Deprecated constants reported by HA 2024.1.2

### ISSUE THREAD

**Issue by friesoft** [h4de5/home-assistant-toshiba_ac#169] opened 2024-01-07 22:24 UTC
Using HA 2024.1.2 I get the following warning messages in log about deprecated constants:
```
2024-01-07 23:19:10.056 WARNING (MainThread) [homeassistant.const] ENERGY_WATT_HOUR was used from toshiba_ac, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.WATT_HOUR instead, please create a bug report at https://github.com/h4de5/home-assistant-toshiba_ac/issues
2024-01-07 23:19:10.064 WARNING (MainThread) [homeassistant.const] TEMP_CELSIUS was used from toshiba_ac, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/h4de5/home-assistant-toshiba_ac/issues
```

**Comment by chrisandsally** [comment] 2024-01-07 22:40
I think this a duplicate of #168

**Closed** 2024-01-08 07:19 UTC

**Comment by friesoft** [comment] 2024-01-08 07:20
Sorry you are right, don't know why I didn't see the other one...
