### ISSUE TITLE
Toshiba_AC integration not work after HA update

### ISSUE THREAD

**Issue by dpoposki79** [h4de5/home-assistant-toshiba_ac#136] opened 2023-08-02 21:48 UTC
Hi,
Toshiba integration is not working after update to HA 2023.8.0. I remove existing entity and add new one with existing Toshiba account, and it said devices or entities.

**Comment by kloboucek** [comment] 2023-08-03 05:54
Same issue here, no devices or entities are being provided by the integration anymore. I'm no developer, so I'll be patiently waiting for this to get fixed, however I can offer help if any testing is required. Thanks.

**Comment by h4de5** [comment] 2023-08-03 06:38
duplicate of #135

**Closed by h4de5** 2023-08-03 06:38 UTC
