### ISSUE TITLE
Lost sensors after upgrading HA core

### ISSUE THREAD

**Issue by jvik** [h4de5/home-assistant-toshiba_ac#36] opened 2022-01-20 20:24 UTC
After updating to core-2021.12.10 the sensors went offline. I tried deleting and re-adding the integration, but no devices or sensors are found. The toshiba ac app on my phone works fine.

**Comment by h4de5** [comment] 2022-01-20 22:56
possible duplicate of #33

**Closed** 2022-01-22 18:15 UTC

**Comment by h4de5** [comment] 2022-01-22 18:16
Add a new release - let me know if the problem is fixed.
