### ISSUE TITLE
Invalid authentication

### ISSUE THREAD

**Issue by perkinskit** [h4de5/home-assistant-toshiba_ac#81] opened 2022-07-28 20:23 UTC
Hello!

Setting up the integration for the first time. When I enter my credentials, I get "Invalid authentication". If I try directly to the API I get:

( 'ResObj' => array ( 'error' => 'invalid_grant', ), 'IsSuccess' => false, 'Message' => 'Invalid UserName or Password', 'StatusCode' => 'InvalidUserNameorPassword', )

I tried deleting my account and creating a fresh one with a different email address and password, and the issue persists.

Any ideas?

Thanks!

[EDIT] - I should mention that I can login to the app "Toshiba AC NA" and control my AC just fine.

**Comment by h4de5** [comment] 2022-07-28 23:58
possible duplicate of #53

**Closed by h4de5** 2022-07-28 23:58 UTC
